# Generated by Django 5.0.2 on 2024-03-11 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_stamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='message',
        ),
        migrations.AddField(
            model_name='chat',
            name='stamp',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
