# Generated by Django 5.0.2 on 2024-03-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_chat_message_chat_stamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stamp',
            name='image_path',
        ),
        migrations.AddField(
            model_name='stamp',
            name='image',
            field=models.ImageField(null=True, upload_to='stamps/'),
        ),
    ]
