# Generated by Django 5.0.2 on 2024-03-16 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_stamp_image_path_stamp_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stamp',
            old_name='stamp_name',
            new_name='stamp',
        ),
        migrations.AlterField(
            model_name='chat',
            name='stamp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.stamp'),
        ),
    ]
