# Generated by Django 5.0.2 on 2024-03-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_stamp_name_stamp_stamp_alter_chat_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='receive_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
