# Generated by Django 5.0.2 on 2024-03-30 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_friendship_receive_notifications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stamp',
            old_name='image',
            new_name='image_path',
        ),
        migrations.RenameField(
            model_name='stamp',
            old_name='stamp',
            new_name='stamp_name',
        ),
    ]
