# Generated by Django 5.0.2 on 2024-04-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_rename_recipient_chat_friend_rename_sender_chat_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendsettings',
            name='nickname',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
